const AUTH_ACTION_TYPES = {
  ERROR: 'ERROR',
  SIGN_UP: 'SIGN_UP',
  SIGN_IN: 'SIGN_IN',
  SIGN_OUT: 'SIGN_OUT',
};

const CANDIDATE_ACTION_TYPES = {
  TOKEN_IS_VALID: 'TOKEN_IS_VALID',

}

export {
  AUTH_ACTION_TYPES,
  CANDIDATE_ACTION_TYPES
};
