const AUTH_ACTION_TYPES = {
  ERROR: 'ERROR',
  SIGN_UP: 'SIGN_UP',
  SIGN_IN: 'SIGN_IN',
  SIGN_OUT: 'SIGN_OUT',
};

const COMPANY_ACTION_TYPES = {
  UPDATE: 'COMPANY/UPDATE',
};

export {
  AUTH_ACTION_TYPES,
  COMPANY_ACTION_TYPES,
};
